// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoryThreads.Models;

namespace StoryThreads.Migrations
{
    [DbContext(typeof(StoryThreadsContext))]
    partial class StoryThreadsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoryThreads.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age");

                    b.Property<string>("Complextion");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Degrees");

                    b.Property<string>("Description");

                    b.Property<string>("EyeColor");

                    b.Property<string>("FirstNames");

                    b.Property<string>("HairColor");

                    b.Property<string>("MetricHeight");

                    b.Property<string>("MetricWeight");

                    b.Property<string>("MiddleNames");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Prefix");

                    b.Property<string>("Sex");

                    b.Property<string>("Suffix");

                    b.Property<string>("Surname");

                    b.Property<string>("Title");

                    b.HasKey("ProfileId");

                    b.ToTable("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
